
package inf_and_code;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
/**
 *
 * @author Heshan
 */
public class customerssignup extends javax.swing.JFrame {

    /**
     * Creates new form customerssignup
     */
    public customerssignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userSnamebox = new javax.swing.JTextField();
        passSwordbox = new javax.swing.JPasswordField();
        cusSbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bctologin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(770, 310));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setDisplayedMnemonic('C');
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Customers Sign Up");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 180, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 82, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        userSnamebox.setBackground(new java.awt.Color(255, 255, 255));
        userSnamebox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userSnamebox.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(userSnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 160, -1));

        passSwordbox.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(passSwordbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 160, -1));

        cusSbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cusSbtn.setForeground(new java.awt.Color(0, 0, 0));
        cusSbtn.setText("Sign Up");
        cusSbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusSbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cusSbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("I have an account");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 60));

        bctologin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bctologin.setForeground(new java.awt.Color(255, 51, 51));
        bctologin.setText("Login");
        bctologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bctologinActionPerformed(evt);
            }
        });
        getContentPane().add(bctologin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf_and_code/AllLoginBackground.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 310));

        setSize(new java.awt.Dimension(784, 318));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cusSbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusSbtnActionPerformed

        String Username, Password, query;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/airline_system";
        SUser = "root";
        SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            if("".equals(userSnamebox.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "User Name is require", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(passSwordbox.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Password is require", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else {
            Username = userSnamebox.getText(); 
            Password = passSwordbox.getText();
            System.out.println(Password);
            
            query = "INSERT INTO customers(uname,upass)"+
                    "VALUES('"+Username+"', '"+Password +"')";
            
            st.execute(query);
            userSnamebox.setText("");
            passSwordbox.setText("");
            showMessageDialog(null, "New account has been created successfully!");
            }
        }catch(Exception e){
           System.out.println("Error!" + e.getMessage()); 
        }
    }//GEN-LAST:event_cusSbtnActionPerformed

    private void bctologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bctologinActionPerformed
            customerslogin m1 = new customerslogin();
            m1.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_bctologinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerssignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerssignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerssignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerssignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerssignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bctologin;
    private javax.swing.JButton cusSbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField passSwordbox;
    private javax.swing.JTextField userSnamebox;
    // End of variables declaration//GEN-END:variables
}
